name: Run Vitest

on:
  pull_request:
    branches: [ "master", "staging"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the Node.js version needed

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run run
